server:
  port: 6325
dubbo:
  application:
    name: dubbo-nacos-consumer
    service-discovery:
      migration: APPLICATION_FIRST
    qos-port: 22223
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://0.0.0.0:8848
    username: nacos
    password: nacos
    parameters:
      namespace: 6cd00e00-7657-49f3-b97a-51e56c30f1ff
      group: dubbo-demo
  config-center:
    timeout: 12000


